### ISSUE TITLE
Hantera undantag från bokningar enligt schema

### ISSUE THREAD

**Issue by Majsvaffla** [Majsvaffla/friskis#3]
Tänk om jag vill gå på konsert istället för på skivstång en specifik fredag. Det hade varit praktiskt om det räckte med att jag avbokade passet manuellt via hemsidan.

Jag har valt att låta ett cronjob köra `book` en gång i timmen och bokar då de av mina pass jag inte är inbokad på. Om jag avbokar ett pass manuellt via hemsidan kommer jag alltså bokas in på passet på nytt inom nästa timme.

Hade jag bara haft ett pass på mitt schema hade det gått att lösa genom att justera tiden när mitt cronjob körs så att den bara bokar in mig på passet strax efter att det har passerat veckan innan. Nu råkar jag ha fler pass på mitt schema så `book` skulle behöva vara smartare så att den kan köras hur ofta som helst men bara boka in passen på schemat om de nyligen har passerat.

**Comment by nip3o** [comment]
Är inte detta löst genom 84005d620a7dd46dbaabeee0749a9033a5356781?

**Comment by Majsvaffla** [comment]
Det är det!
